name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: |
              IMAGE_NAME_AUTHOR=ghcr.io/${{ github.repository_owner }} \
              IMAGE_NAME_AUTHOR=$(echo "$IMAGE_NAME_AUTHOR" | tr '[:upper:]' '[:lower:]')
              docker build -t $IMAGE_NAME_AUTHOR/dotnet-app:latest ./dotnet-app

      - name: Push Docker image to GHCR
        run: |
              IMAGE_NAME_AUTHOR=ghcr.io/${{ github.repository_owner }} \
              IMAGE_NAME_AUTHOR=$(echo "$IMAGE_NAME_AUTHOR" | tr '[:upper:]' '[:lower:]')
              docker push $IMAGE_NAME_AUTHOR/dotnet-app:latest